# Generated by Django 5.2.7 on 2026-01-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_application_recruiter_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv_file',
        ),
        migrations.AddField(
            model_name='application',
            name='cv_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
