# Generated by Django 4.2.27 on 2026-01-04 02:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_age_applicant_dob_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('OTHER', 'Khác')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
