# Generated by Django 4.2.27 on 2026-01-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_applicant_dob_alter_applicant_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
